output_dir = "dist"
content_dir = "appunti"

[home]
content = """
Questi appunti sono stati presi da [me](https://leoflo.me).
Potrebbero esserci errori di qualunque genere, perciò attenti e confrontate sempre tutto ciò che leggete, specialmente da siti come questi.
Se vuoi vedere come funziona questo sito, visita la repository su [GitHub](https://github.com/le0flo/appunti.leoflo.me).
"""

[pages]
header = """
<script
    id="MathJax-script"
    async
    src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
></script>
<script>
    MathJax = {
        tex: {
            displayMath: [["\\$\\$", "\\$\\$"]],
            inlineMath: [["\\$", "\\$"]],
        },
        loader: {
            load: ["ui/safe"],
        },
    };
</script>
"""
