baseURL = 'https://appunti.leoflo.me'
languageCode = 'it-IT'
title = 'Appunti'
theme = 'hugo-book'

disablePathToLower = true

[params]
math = true
BookTheme = 'light'
BookToC = false
BookSection = 'appunti'
BookSearch = true

[params.meta]
favicon = false

[markup]
highlight.codeFences = false

[markup.tableOfContents]
endLevel = 4
startLevel = 1

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$']]
inline = [['$', '$']]