baseURL = 'https://appunti.leoflo.me'
languageCode = 'it-IT'
title = 'Appunti'
theme = 'hugo-book'

disablePathToLower = true

[markup.tableOfContents]
endLevel = 4
startLevel = 1

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$']]
inline = [['$', '$']]

[params]
math = true
BookTheme = 'light'
BookToC = true
BookLogo = 'favicon.png'
BookSection = 'appunti'
BookDateFormat = 'Jan 2, 2006'
BookSearch = true
BookRepo = 'https://github.com/le0flo/appunti'
BookCommitPath = 'commit'

[params.meta]
favicon = false